-- MySQL Script generated by MySQL Workbench
-- 08/17/15 18:49:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema r_mysql_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema r_mysql_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `r_mysql_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `r_mysql_test` ;

-- -----------------------------------------------------
-- Table `r_mysql_test`.`PERSON_ID2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r_mysql_test`.`PERSON_ID2` (
  `PERSON_ID` INT(8) NOT NULL,
  PRIMARY KEY (`PERSON_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r_mysql_test`.`SPperson_id2ECIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r_mysql_test`.`SPECIFICATION` (
  `PERSON_ID` INT(8) NOT NULL,
  `KEY_CODE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PERSON_ID`, `KEY_CODE`),
  INDEX `fk_SPECIFICATION_PERSON_ID2_idx` (`PERSON_ID` ASC),
  CONSTRAINT `fk_SPECIFICATION_PERSON_ID2`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `r_mysql_test`.`PERSON_ID2` (`PERSON_ID`)
    /*ON DELETE NO ACTION
    ON UPDATE NO ACTION*/)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
