-- MySQL Script generated by MySQL Workbench
-- 08/10/15 13:58:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MPDatabase
-- -----------------------------------------------------
-- Korea Data Base -P- Project Data Base in MySQL

-- -----------------------------------------------------
-- Schema MPDatabase
--
-- Korea Data Base -P- Project Data Base in MySQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MPDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MPDatabase` ;

-- -----------------------------------------------------
-- Table `MPDatabase`.`SPECIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPDatabase`.`SPECIFICATION` (
  `PERSON_ID` INT(8) NOT NULL COMMENT '',
  `KEY_SEQ` VARCHAR(12) NOT NULL COMMENT '',
  `YKIHO_ID` INT(6) NULL COMMENT '',
  `RECU_FR_DT` VARCHAR(8) NOT NULL COMMENT '',
  `FORM_CD` VARCHAR(2) NULL COMMENT '',
  `DSBJT_CD` VARCHAR(2) NULL COMMENT '',
  `MAIN_SICK` VARCHAR(6) NULL COMMENT '',
  `SUB_SICK` VARCHAR(6) NULL COMMENT '',
  `IN_PAT_CORS_TYPE` VARCHAR(2) NULL COMMENT '',
  `OFFC_INJ_TYPE` VARCHAR(1) NULL COMMENT '',
  `RECN` INT(3) NULL COMMENT '',
  `VSCN` INT(3) NULL COMMENT '',
  `FST_IN_PAT_DT` VARCHAR(8) NULL COMMENT '',
  `DMD_TRAMT` INT(8) NULL COMMENT '',
  `DMD_SBRDN_AMT` INT(8) NULL COMMENT '',
  `DMD_JBRDN_AMT` INT(8) NULL COMMENT '',
  `DMD_CT_TOT_AMT` INT(8) NULL COMMENT '',
  `DMD_MRI_TOT_AMT` INT(8) NULL COMMENT '',
  `EDEC_ADD_RT` INT(3) NULL COMMENT '',
  `EDEC_TRAMT` INT(8) NULL COMMENT '',
  `EDEC_SBRDN_AMT` INT(8) NULL COMMENT '',
  `EDEC_JBRDN_AMT` INT(8) NULL COMMENT '',
  `EDEC_CT_TOT_AMT` INT(8) NULL COMMENT '',
  `EDEC_MRI_TOT_AMT` INT(8) NULL COMMENT '',
  `DMD_DRG_NO` VARCHAR(10) NULL COMMENT '',
  `MPRSC_ISSUE_ADMIN_ID` INT(6) NULL COMMENT '',
  `MPRSC_GRANT_NO` VARCHAR(13) NULL COMMENT '',
  `TOT_PRES_DD_CNT` INT(3) NULL COMMENT '',
  PRIMARY KEY (`PERSON_ID`, `KEY_SEQ`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPDatabase`.`MEDICAL_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPDatabase`.`MEDICAL_HISTORY` (
  `KEY_SEQ` VARCHAR(12) NOT NULL COMMENT '',
  `SEQ_NO` INT(4) NULL COMMENT '',
  `RECU_FR_DT` VARCHAR(8) NULL COMMENT '',
  `CLAUSE_CD` VARCHAR(2) NULL COMMENT '',
  `ITEM_CD` VARCHAR(2) NULL COMMENT '',
  `DIV_TYPE_CD` VARCHAR(1) NULL COMMENT '',
  `DIV_CD` VARCHAR(9) NULL COMMENT '',
  `I_II_TYPE` VARCHAR(1) NULL COMMENT '',
  `UN_COST` INT(8) NULL COMMENT '',
  `AMT` INT(8) NULL COMMENT '',
  `DD_MQTY_EXEC_FREQ` INT(8) NULL COMMENT '',
  `MDCN_EXEC_FREQ` INT(8) NULL COMMENT '',
  `DD_MQTY_FREQ` INT(8) NULL COMMENT '',
  PRIMARY KEY (`KEY_SEQ`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPDatabase`.`SB_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPDatabase`.`SB_HISTORY` (
  `KEY_SEQ` VARCHAR(12) NOT NULL COMMENT '',
  `SEQ_NO` INT(4) NULL COMMENT '',
  `RECU_FR_DT` VARCHAR(8) NULL COMMENT '',
  `DSBJT_CD` VARCHAR(2) NULL COMMENT '',
  `SICK_SYM` VARCHAR(6) NULL COMMENT '',
  PRIMARY KEY (`KEY_SEQ`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPDatabase`.`진료DB처방전교부상세내역`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPDatabase`.`진료DB처방전교부상세내역` (
  `KEY_SEQ` VARCHAR(12) NOT NULL COMMENT '',
  `SEQ_NO` INT(4) NULL COMMENT '',
  `RECU_FR_DT` VARCHAR(8) NULL COMMENT '',
  `DIV_TYPE_CD` VARCHAR(1) NULL COMMENT '',
  `DIV_CD` VARCHAR(9) NULL COMMENT '',
  `GNL_NM_CD` VARCHAR(9) NULL COMMENT '',
  `DD_MQTY_FREQ` INT(8) NULL COMMENT '',
  `DD_EXEC_FREQ` INT(8) NULL COMMENT '',
  `MDCN_EXEC_FREQ` INT(8) NULL COMMENT '',
  `UN_COST` INT(8) NULL COMMENT '',
  `AMT` INT(8) NULL COMMENT '',
  PRIMARY KEY (`KEY_SEQ`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MPDatabase`.`자격DB레이아웃`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MPDatabase`.`자격DB레이아웃` (
  `STND_Y` VARCHAR(4) NULL COMMENT '',
  `PERSON_ID` INT(8) NOT NULL COMMENT '',
  `SEX` VARCHAR(1) NULL COMMENT '',
  `AGE_GROUP` VARCHAR(2) NULL COMMENT '',
  `DTH_YM` VARCHAR(6) NULL COMMENT '',
  `DTH_CODE1` VARCHAR(14) NULL COMMENT '',
  `DTH_CODE2` VARCHAR(14) NULL COMMENT '',
  `SIDO` VARCHAR(2) NULL COMMENT '',
  `SGG` VARCHAR(5) NULL COMMENT '',
  `IPSN_TYPE_CD` VARCHAR(1) NULL COMMENT '',
  `CTRB_PT_TYPE_CD` VARCHAR(2) NULL COMMENT '',
  `DFAB_GRD_CD` VARCHAR(1) NULL COMMENT '',
  `DFAB_PTN_CD` VARCHAR(1) NULL COMMENT '',
  `DFAV_REG_YM` VARCHAR(6) NULL COMMENT '',
  PRIMARY KEY (`PERSON_ID`)  COMMENT '')
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;